name: Release
on:
  push:
    tags: 
      - '*'

jobs:
  release:
    uses: quenktechnologies/.github/.github/workflows/node-publish.yml@master
    secrets: inherit
    with:
      setup: "apt-get install -y mongodb"
