name: Release
on:
  push:
    tags: 
      - '*'

jobs:
  release:
    uses: quenktechnologies/.github/.github/workflows/node-publish.yml@master
    secrets: inherit
    with:
      setup: "wget -qO- https://gist.githubusercontent.com/metasansana/36c816cb3435345d764fafac4805983c/raw/5a09b5a375155584a1db72f7adadb115f6227a85/install_mongodb.sh | bash"
