name: Test
on:
  push:
    branches: 
      - master

jobs:
  release:
    uses: quenktechnologies/.github/.github/workflows/node-build.yml@master
    secrets: inherit
    with:
      setup: "sudo apt-get install -y mongodb"
