name: Test
on:
  push:
    branches: 
      - master

jobs:
  release:
    uses: quenktechnologies/.github/.github/workflows/node-build.yml@master
    secrets: inherit
    with:
      setup: "wget -qO- https://gist.githubusercontent.com/metasansana/36c816cb3435345d764fafac4805983c/raw/7347d508dcd5a1ba57cd275d15ef84c8e642f00e/install_mongodb.sh | bash"
