name: Test
on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install mongodb -y
      - name: build
        uses: quenktechnologies/.github/.github/workflows/node-build.yml@master
        secrets: inherit
